/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tamagui;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Enumeration;
import javax.swing.AbstractButton;


/**
 *
 * @author Christian
 */
public class addTask extends javax.swing.JFrame {
    private String taskName;
    private String difficulty;
    private String dueDate;
    private String dueTime;
    private final Error error;
    private TamaGuiHome home;
    private boolean isEditTask;
    
    /**
     * Creates new form addTask
     * @param tamaGuiHome
     */
    public addTask(TamaGuiHome tamaGuiHome) {
        initComponents();
        error = new Error();
        home = tamaGuiHome;
        this.isEditTask = false;
    }
    
    public addTask(TamaGuiHome tamaGuiHome, String taskName, String difficulty, String dueDate, String dueTime) {
        initComponents();
        error = new Error();
        home = tamaGuiHome;
        this.TaskName.setText(taskName);
        this.dueDateField.setText(dueDate);
        this.dueTimeField.setText(dueTime);
        this.AddTaskLabel.setText("Edit Task");
        switch (difficulty) {
            case "Easy" -> this.Easy.setSelected(true);
            case "Medium" -> this.Medium.setSelected(true);
            default -> this.Hard.setSelected(true);
        }
        this.isEditTask = true;
    }
    
    private String getSelectedDifficulty()
    {  
        Enumeration<AbstractButton> difficultyButtons = Difficulty.getElements();
        while (difficultyButtons.hasMoreElements()) {
            AbstractButton difficultyButton = difficultyButtons.nextElement();
            if (difficultyButton.isSelected()) {
                    return difficultyButton.getText();
            }
        }
        return null;
    }

    private String validateTaskName(String taskName) {
        if (taskName == null || taskName.isEmpty()){
            return "Task Name is empty";
        }
        if (taskName.indexOf('-') > -1){
            return "Task Name cannot contains special character '-'";
        }
        return "";
    }
    
    private String validateDueDate(String dueDate) {
        if (dueDate == null || dueDate.isEmpty()){
            return "Due Date is empty";
        }
        String []dueDates = dueDate.split("/");
        if (dueDates.length != 3){
            return "Due Date needs to be in mm/dd/yyyy";
        }
        return "";
    }
    
    private String validateDueTime(String dueTime) {
        if (dueTime == null || dueTime.isEmpty()){
            return "Due Time is empty";
        }
        String []dueTimes = dueTime.split(":");
        if (dueTimes.length != 2){
            return "Due Time needs to be in hh:mm";
        }
        return "";
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Difficulty = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        TaskName = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        dueDateField = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        dueTimeField = new javax.swing.JTextPane();
        AddTaskLabel = new javax.swing.JLabel();
        DueTimeLabel = new javax.swing.JLabel();
        TaskDifficultyLabel = new javax.swing.JLabel();
        CompleteByLabel = new javax.swing.JLabel();
        Easy = new javax.swing.JCheckBox();
        Medium = new javax.swing.JCheckBox();
        Hard = new javax.swing.JCheckBox();
        Done = new javax.swing.JButton();
        TaskNameLabel = new javax.swing.JLabel();
        DueDateLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(TaskName);

        jScrollPane3.setViewportView(dueDateField);

        jScrollPane2.setViewportView(dueTimeField);

        AddTaskLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        AddTaskLabel.setText("Add Task");

        DueTimeLabel.setText("Due Time (hh:mm) :");

        TaskDifficultyLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        TaskDifficultyLabel.setText("Choose Task Difficulty");

        CompleteByLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        CompleteByLabel.setText("Complete By:");

        Difficulty.add(Easy);
        Easy.setText("Easy");

        Difficulty.add(Medium);
        Medium.setText("Medium");

        Difficulty.add(Hard);
        Hard.setText("Hard");

        Done.setText("Done");
        Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneActionPerformed(evt);
            }
        });

        TaskNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        TaskNameLabel.setText("Task Name");

        DueDateLabel.setText("Due Date (mm/dd/yyyy) :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddTaskLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Done)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Medium)
                            .addComponent(Hard)
                            .addComponent(Easy)
                            .addComponent(TaskDifficultyLabel)
                            .addComponent(TaskNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CompleteByLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DueDateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(DueTimeLabel)
                                .addGap(39, 39, 39)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(18, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(AddTaskLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TaskNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TaskDifficultyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Easy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Medium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hard)
                .addGap(18, 18, 18)
                .addComponent(CompleteByLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DueDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DueTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(Done)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //Done Button
    private void DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneActionPerformed
       
        //Sets task Name. Pops error message if field is empty
        taskName = TaskName.getText().trim();
        String errMsg = validateTaskName(taskName);
        if (!errMsg.equals("")){
            error.SetErrorMsg(errMsg);
            error.setVisible(true);
            return;
        }
        difficulty = getSelectedDifficulty();
        if (difficulty == null || difficulty.isEmpty()){
            error.SetErrorMsg("Difficulty is not selected");
            error.setVisible(true);
            return;
        }
        
        // Date validation
        dueDate = dueDateField.getText().trim();
        errMsg = validateDueDate(dueDate);
        if (!errMsg.equals("")){
            error.SetErrorMsg(errMsg);
            error.setVisible(true);
            return;
        }
        // Time validation
        dueTime = dueTimeField.getText().trim();
        errMsg = validateDueTime(dueTime);
        if (!errMsg.equals("")){
            error.SetErrorMsg(errMsg);
            error.setVisible(true);
            return;
        }
        
        // TODO: Check if we can save DATE object 
        String taskDate = dueDate + " "+ dueTime;
        Date dateFormat;
        try {
            dateFormat =new SimpleDateFormat("mm/dd/yyyy HH:mm").parse(taskDate);  
  
        } catch(Exception e){ 
            error.SetErrorMsg(e.getMessage());
            error.setVisible(true);
            return;
        }
        
        Task newTask = new Task(taskName, difficulty, dueDate, dueTime);
        home.addTask(newTask);
        System.out.println("Adding Task: "+ newTask.toString());
        // Close the addTask window -- Last thing to run when "Done" is pressed.
        // Update points if it is not edit task
        if (!this.isEditTask){
            home.addPoints(1);
            Error error = new Error();
            error.SetErrorMsg("Task added.Points gained: 1");
            error.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_DoneActionPerformed

// Set method for taskName
public  void setTaskName(String taskName){
    this.TaskName.setText(taskName);
}

    
// Get method for taskName
public String getTaskName(){
    return taskName;
}

// Get method for difficulty
public String getDifficulty() {
    return difficulty;
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddTaskLabel;
    private javax.swing.JLabel CompleteByLabel;
    private javax.swing.ButtonGroup Difficulty;
    private javax.swing.JButton Done;
    private javax.swing.JLabel DueDateLabel;
    private javax.swing.JLabel DueTimeLabel;
    private javax.swing.JCheckBox Easy;
    private javax.swing.JCheckBox Hard;
    private javax.swing.JCheckBox Medium;
    private javax.swing.JLabel TaskDifficultyLabel;
    private javax.swing.JTextPane TaskName;
    private javax.swing.JLabel TaskNameLabel;
    private javax.swing.JTextPane dueDateField;
    private javax.swing.JTextPane dueTimeField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
