/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tamagui;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Maya
 */
public final class InventoryFood extends javax.swing.JFrame {
    private final TamaGuiHome  home;
    private final Item[] inventory; 
    /**
     * Creates new form InteractionFeed
     * @param home
     */
    public InventoryFood(TamaGuiHome home) {
        initComponents();
        this.home = home;
        Item [] items = {
            new Item("Peppermint",1,2,0),
            new Item("Lollipop",3,5,0),
            new Item("Toffee",5,8,0),
            new Item("Chocolate",7,11,0),
            new Item("Donut",9,15,0),
            };
        this.inventory = items;
        addFeeds(items);
        BoostName.setVisible(false);
        BoostValue.setVisible(false);
        Cost.setVisible(false);
        CostValue.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Feed = new javax.swing.JPanel();
        FeedPanel = new javax.swing.JScrollPane();
        FeedList = new javax.swing.JList<>();
        useItem = new javax.swing.JButton();
        FeedImage = new javax.swing.JLabel();
        Cost = new javax.swing.JLabel();
        CostValue = new javax.swing.JLabel();
        BoostName = new javax.swing.JLabel();
        BoostValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TaskFriend Feed's");

        FeedList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                FeedListValueChanged(evt);
            }
        });
        FeedPanel.setViewportView(FeedList);

        useItem.setText("Use Item");
        useItem.setToolTipText("Feed your TaskFriend to increase his fullness.");
        useItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useItemActionPerformed(evt);
            }
        });

        Cost.setText("Cost:");

        CostValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CostValue.setText("00");

        BoostName.setText("Fullness:");

        BoostValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BoostValue.setText("00");

        javax.swing.GroupLayout FeedLayout = new javax.swing.GroupLayout(Feed);
        Feed.setLayout(FeedLayout);
        FeedLayout.setHorizontalGroup(
            FeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(FeedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(FeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FeedLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(FeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FeedLayout.createSequentialGroup()
                                .addComponent(BoostName, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BoostValue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FeedLayout.createSequentialGroup()
                                    .addComponent(Cost, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(CostValue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(useItem, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(FeedLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(FeedImage, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        FeedLayout.setVerticalGroup(
            FeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FeedLayout.createSequentialGroup()
                .addGroup(FeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FeedPanel)
                    .addGroup(FeedLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FeedImage, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(FeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BoostName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoostValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cost)
                            .addComponent(CostValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(useItem)))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Feed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Feed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void useItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useItemActionPerformed
        String feed = FeedList.getSelectedValue();
        if (feed == null || feed.isEmpty()){
            Error error = new Error();
            error.SetErrorMsg("Select the feed");
            error.setVisible(true);
            return;
        }
        int availablePoints = this.home.getPoints();
        // Find item from inventory
        Item selectedItem = this.inventory[0];
        boolean found=false;
        for (Item item : this.inventory) {
            if (feed.equals(item.getName())) {
                selectedItem =  item;
                found = true;
            }
        }
        if (found == false) {
            Error error = new Error();
            error.SetErrorMsg("Could not load inventory");
            error.setVisible(true);
            return;
        }
        if (availablePoints < selectedItem.getCost()) {
            Error error = new Error();
            error.SetErrorMsg("Insufficient points");
            error.setVisible(true);
            return;
        } else {
            this.home.addPoints(-1*selectedItem.getCost());
        }
        this.home.updateFullness(selectedItem.getBoost_1());
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_useItemActionPerformed

    private void FeedListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_FeedListValueChanged
        String food = FeedList.getSelectedValue();
        String foodIconPath = "Images/Food/" + food + ".png";
        ImageIcon foodIcon = new ImageIcon(new ImageIcon(foodIconPath).getImage().getScaledInstance(120, 200, Image.SCALE_DEFAULT));
        FeedImage.setIcon(foodIcon); 
        FeedImage.setVisible(true);
        // Find item from inventory
        Item selectedItem = this.inventory[0];
        boolean found=false;
        for (Item item : this.inventory) {
            if (food.equals(item.getName())) {
                selectedItem =  item;
                found = true;
            }
        }
        if (found == false) {
            Error error = new Error();
            error.SetErrorMsg("Could not load inventory");
            error.setVisible(true);
            return;
        }
        CostValue.setText(String.valueOf(selectedItem.getCost()));
        BoostValue.setText("+"+String.valueOf(selectedItem.getBoost_1()));
        BoostName.setVisible(true);
        BoostValue.setVisible(true);
        Cost.setVisible(true);
        CostValue.setVisible(true);
    }//GEN-LAST:event_FeedListValueChanged

    public void addFeeds(Item[] items){
       FeedList.setModel(new javax.swing.AbstractListModel<String>() {
            @Override
            public int getSize() { return items.length; }
            @Override
            public String getElementAt(int i) { return items[i].getName(); }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BoostName;
    private javax.swing.JLabel BoostValue;
    private javax.swing.JLabel Cost;
    private javax.swing.JLabel CostValue;
    private javax.swing.JPanel Feed;
    private javax.swing.JLabel FeedImage;
    private javax.swing.JList<String> FeedList;
    private javax.swing.JScrollPane FeedPanel;
    private javax.swing.JButton useItem;
    // End of variables declaration//GEN-END:variables
}
