/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tamagui;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Arpita Sakshee
 */
public final class InventoryAvatar extends javax.swing.JFrame {
    private final TamaGuiHome home;
    private final Item[] inventory; 
    /**
     * Creates new form InventoryAvatar
     * @param home
     */
    public InventoryAvatar(TamaGuiHome home) {
        initComponents();
        this.home = home;
          Item [] items = {
            new Item("Ozzo",30,0,0),
            new Item("Shey",30,0,0),
            new Item("Milo",30,0,0),
            new Item("Petunia",30,0,0),
            new Item("Tee",30,0,0),
        };
        addAvatars(items);
        this.inventory = items;
        Cost.setVisible(false);
        CostValue.setVisible(false);
    }
    
    public void addAvatars(Item[] items){
       AvatarList.setModel(new javax.swing.AbstractListModel<String>() {
            @Override
            public int getSize() { return items.length; }
            @Override
            public String getElementAt(int i) { return items[i].getName(); }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Avatar = new javax.swing.JPanel();
        AvatarPanel = new javax.swing.JScrollPane();
        AvatarList = new javax.swing.JList<>();
        SelectAvatar = new javax.swing.JButton();
        AvatarImage = new javax.swing.JLabel();
        Cost = new javax.swing.JLabel();
        CostValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change TaskFriend");

        AvatarList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                AvatarListValueChanged(evt);
            }
        });
        AvatarPanel.setViewportView(AvatarList);

        SelectAvatar.setText("Select TaskFriend");
        SelectAvatar.setToolTipText("Select Task Friend to change.");
        SelectAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectAvatarActionPerformed(evt);
            }
        });

        Cost.setText("Cost:");

        CostValue.setText("00");

        javax.swing.GroupLayout AvatarLayout = new javax.swing.GroupLayout(Avatar);
        Avatar.setLayout(AvatarLayout);
        AvatarLayout.setHorizontalGroup(
            AvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AvatarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AvatarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(AvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AvatarLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Cost, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(CostValue, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AvatarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(AvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SelectAvatar)
                            .addComponent(AvatarImage, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        AvatarLayout.setVerticalGroup(
            AvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AvatarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AvatarPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AvatarLayout.createSequentialGroup()
                        .addComponent(AvatarImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(32, 32, 32)
                        .addGroup(AvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cost, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CostValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SelectAvatar)))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Avatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelectAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectAvatarActionPerformed
        String avatarName = AvatarList.getSelectedValue();
        if (avatarName == null || avatarName.isEmpty()){
            Error error = new Error();
            error.SetErrorMsg("Select the TaskFriend");
            error.setVisible(true);
            return;
        }
        // Find item from inventory
        Item selectedItem = this.inventory[0];
        boolean found=false;
        for (Item item : this.inventory) {
            if (avatarName.equals(item.getName())) {
                selectedItem =  item;
                found = true;
            }
        }
        if (found == false) {
            Error error = new Error();
            error.SetErrorMsg("Could not load inventory");
            error.setVisible(true);
            return;
        }
        int availablePoints = this.home.getPoints();
        if (availablePoints < selectedItem.getCost()) {
            Error error = new Error();
            error.SetErrorMsg("Insufficient points");
            error.setVisible(true);
            return;
        } else {
            this.home.addPoints(-1*selectedItem.getCost());
        }
        String health = home.getHealth();
        String accessory = home.getAccessory();
        String avatarImagePath =  "Images/Avatar/"+ health + "/"+ accessory+"/" +avatarName+ ".png"; 
        this.home.updateAvatar(avatarImagePath, avatarName);
        this.setVisible(false);
        System.out.println("Selecting avatar: "+ avatarImagePath);
        this.dispose();
    }//GEN-LAST:event_SelectAvatarActionPerformed

    private void AvatarListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_AvatarListValueChanged
        String avatar = AvatarList.getSelectedValue();
        String accessory = home.getAccessory();
        String health = home.getHealth();
        String avatarIconPath =  "Images/Avatar/"+ health + "/"+ accessory+"/" +avatar+ ".png"; 
        ImageIcon avatarIcon = new ImageIcon(new ImageIcon(avatarIconPath).getImage().getScaledInstance(120, 200, Image.SCALE_DEFAULT));
        AvatarImage.setIcon(avatarIcon);
        AvatarImage.setVisible(true);
        // Find item from inventory
        Item selectedItem = this.inventory[0];
        boolean found=false;
        for (Item item : this.inventory) {
            if (avatar.equals(item.getName())) {
                selectedItem =  item;
                found = true;
            }
        }
        if (found == false) {
            Error error = new Error();
            error.SetErrorMsg("Could not load inventory");
            error.setVisible(true);
            return;
        }
        CostValue.setText(String.valueOf(selectedItem.getCost()));
        Cost.setVisible(true);
        CostValue.setVisible(true);
    }//GEN-LAST:event_AvatarListValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Avatar;
    private javax.swing.JLabel AvatarImage;
    private javax.swing.JList<String> AvatarList;
    private javax.swing.JScrollPane AvatarPanel;
    private javax.swing.JLabel Cost;
    private javax.swing.JLabel CostValue;
    private javax.swing.JButton SelectAvatar;
    // End of variables declaration//GEN-END:variables
}
