/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tamagui;

import java.util.Random;

/**
 *
 * @author Arpita Sakshee
 */
public class Play extends javax.swing.JFrame {
     private final TamaGuiHome home;

    /**
     * Creates new form Play
     * @param home
     */
    public Play(TamaGuiHome home) {
        initComponents();
        this.home=home;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlayGame = new javax.swing.JLabel();
        PlayInfo = new javax.swing.JScrollPane();
        PlayInfoText = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        Guess = new javax.swing.JButton();
        PlayChoice = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        BoostName = new javax.swing.JLabel();
        BoostName1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Play");

        PlayGame.setText("Guess the number");

        PlayInfoText.setEditable(false);
        PlayInfoText.setColumns(20);
        PlayInfoText.setLineWrap(true);
        PlayInfoText.setRows(5);
        PlayInfoText.setText("Your little friend will give you a random number between 1-9. Your goal is to guess whether the next number it thinks of will be higher or lower than the 5. Note that it cannot pick a number higher than 9, or lower than 1.");
        PlayInfoText.setWrapStyleWord(true);
        PlayInfo.setViewportView(PlayInfoText);

        Guess.setText("Guess");
        Guess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuessActionPerformed(evt);
            }
        });

        PlayChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Higher", "Lower" }));
        PlayChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayChoiceActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cost: 50");

        BoostName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BoostName.setText("Happiness:  +30");

        BoostName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BoostName1.setText("Entertained:  +10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BoostName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Guess, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PlayChoice, 0, 162, Short.MAX_VALUE)
                    .addComponent(BoostName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PlayChoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BoostName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BoostName1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Guess)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(PlayGame))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PlayInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(PlayGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PlayInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlayChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlayChoiceActionPerformed

    private void GuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuessActionPerformed
        // TODO add your handling code here:
         int availablePoints = this.home.getPoints();
      
        if (availablePoints < 50) {
            Error error = new Error();
            error.SetErrorMsg("Insufficient points");
            error.setVisible(true);
            return;
        } else {
            this.home.addPoints(-50);
        }
        
        Random rand = new Random();
        int guess = rand.nextInt(8)+1; // Random 0-8 +1
        Error error = new Error();
        String userGuess= PlayChoice.getSelectedItem().toString();
        if (("Higher".equals(userGuess)  && guess >5) ||
             ("Lower".equals(userGuess)  && guess <5)) {
            error.SetErrorMsg("Avatar Guess " + guess + ". You WON.");
        } else {
            error.SetErrorMsg("Avatar Guess " + guess + ". You Loss.");
        }
        this.home.updateHappiness(30);
        this.home.updateEntertained(10);
        error.setVisible(true);
    }//GEN-LAST:event_GuessActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BoostName;
    private javax.swing.JLabel BoostName1;
    private javax.swing.JButton Guess;
    private javax.swing.JComboBox<String> PlayChoice;
    private javax.swing.JLabel PlayGame;
    private javax.swing.JScrollPane PlayInfo;
    private javax.swing.JTextArea PlayInfoText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
